### ISSUE TITLE
Вопрос по функционалу «Выручки в магазине»: если все одинаковые

### ISSUE THREAD

**Issue by Lagunov-PRO** [Lagunov-PRO/HW05_Shops_Revenues#2]
@coursar
Если у нас три магазина, и у них одинаковые показатели, то это можно трактовать как:
1. Все они лучшие
2. Никто из них не лучший

Во втором случае можно просто добавить проверку, что 
```
if len(best_shops) == len(shops):
	return None
else:
	return best_shops
```
Или это можно реализовать уже в main() в виде проверяющей функции.

Ваше мнение?

**Comment by coursar** [comment]
я бы вернул список ))
