### ISSUE TITLE
Pytest не видит файл *.txt

### ISSUE THREAD

**Issue by Lagunov-PRO** [Lagunov-PRO/HW05_Shops_Revenues#3]
@coursar , Приветствую!
Я может забегаю вперёд, но я сделал файл txt с данными магазинов, оттуда их построчно считал, разбил на строки, строки на значение, каждое преобразовал в int(), записал в список, сделал список списков, здесь разобрался:
https://github.com/Lagunov-PRO/HW05_Shops_Revenues/blob/070592cbfe82b16719ce80576a76ed3ee0a42c08/app/main.py#L5-L14

Сам файл:
https://github.com/Lagunov-PRO/HW05_Shops_Revenues/blob/070592cbfe82b16719ce80576a76ed3ee0a42c08/app/shops_week_revenues.txt#L1-L3

Программа запускается и отрабатывает.
Но Pytest не видит файла:
`    for all_shops_file in open("shops_week_revenues.txt", 'r', encoding='utf-8'):
E   FileNotFoundError: [Errno 2] No such file or directory: 'shops_week_revenues.txt'
`

Как быть?

**Comment by coursar** [comment]
А зачем вам в рамках Pytest запускать main.py?

**Comment by coursar** [comment]
По факту, надо вынести файл *.txt на уровень выше и запускать:
* из python: `python3 -m app.main`
* из pytest: `pytest`

**Comment by Lagunov-PRO** [comment]
@coursar 

> А зачем вам в рамках Pytest запускать main.py?

Для этого, судя по документации нужно добавить `--ignore=app/main.py ` в `adopts`
Верно?

**Comment by coursar** [comment]
Зачем? )) можно же просто добавить if __name__ == '__main__': и тогда то, что внутри этого if'а запускаться не будет

**Comment by Lagunov-PRO** [comment]
@coursar 
Добавил:
https://github.com/Lagunov-PRO/HW05_Shops_Revenues/blob/9c7e3fd9e86adf99d08b6fffb4402708b1f1b626/app/main.py#L51-L52

> запускаться не будет

Почему не будет, кстати? Где это сконфигурировано?

**Comment by coursar** [comment]
потому что этого пока не проходили, но эта переменная принимает значение '__main__' только если вы запускаете модуль как скрипт, т.е. python main.py
